### ISSUE TITLE
Is this the one that is on Overwolf?

### ISSUE THREAD

**Issue by lmvdz** [llabinator/New-World-MiniMap#1]
Title says it all

**Comment by llabinator** [comment]
This program does not run through Overwolf. It is coded and compiled through Java. Therefore if you have Java 1.8 + (which majority of computers nowadays have) you can just run the .jar file (Minimap.jar). I mainly created this more for fun, and before I knew other people were working on there own, and eventually publishing them to overwolf. I have decided to not further update this program, as other people have better versions out on overwolf. If anyone runs into any bugs, I would gladly help and fix them.

**Comment by llabinator** [comment]
> 
> 
> I had an idea to get the mob data from newworldfans, using the nameplate image ![image](https://user-images.githubusercontent.com/2179775/138163534-446f99b2-ee24-441c-9bcd-6fa333a29df8.png) so you could see how much EXP that mob would give, and the total HP of the mob

That is a good idea, and I've had similar, but the execution would be very hard... But I can try to work something up.

**Comment by llabinator** [comment]
@lmvdz I can get the mobs names and levels, but do you know where to get there HP?
Can't seem to find it in there jsons....

**Comment by llabinator** [comment]
@lmvdz Can you join my discord? We can talk about this further in here or through dms, I am quite interested! [discord](https://discord.gg/YMF3DcxX)

**Comment by lmvdz** [comment]
Cool, interested to see it! One thing I noticed is that the name of the mobs sometimes isn't correct compared to the database... or there are missing creatures.
